# Generated by Django 5.1.4 on 2024-12-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_name', models.CharField(max_length=60)),
                ('post_content', models.CharField(max_length=500)),
                ('post_date', models.DateField()),
            ],
        ),
    ]
